Layer: ""
Type: ""
Latency(C)-No-Depth: -1
Latency(C): -1
Latency(S): -1.0
GOP/s: -1.0
GOPs: -1.0
volumes/s: -1.0
DSPs: -1
DSP(%): -1.0
BRAMs: -1
BRAM(%): -1.0
RateIn: []
RateOut: []
Depth: -1
Branch Depth: -1
Muls: -1
Adds: -1
Mem(W): -1
Mem(KB): -1
DataSizeIn(MB): -1.0
DataSizeOut(MB): -1.0
MemBoundIn: False
MemBoundOut: False
config:
  batch_size: -1
  channels_in: -1
  depth_in: -1
  height_in: -1
  width_in: -1
  channels_out: -1
  depth_out: -1
  height_out: -1
  width_out: -1
  features_in: -1
  features_out: -1
  kernel_depth: -1
  kernel_height: -1
  kernel_width: -1
  weights_rows: -1
  weights_cols: -1
  shape_bias: -1
  pad_depth: -1
  pad_height: -1
  pad_width: -1
  stride_depth: -1
  stride_height: -1
  stride_width: -1
  groups: -1
  depthwise: -1
  pointwise: -1
  broadcasting: -1
  op_type: ""
  fine_factor: -1
  coarse_in_factor: -1
  coarse_out_factor: -1
  coarse_factor: -1