name: fpga_hart_optimization_sweep
method: grid # bayes or random or grid
metric:
  goal: minimize
  name: latency
parameters:
  simulatedAnnealing:
    parameters:
      t_min:
        value: 1e-5
      t_max:
        value: 10
      iterationPerTemp:
        value: 15
      cooling_rate:
        value: 0.985
      best_of_iter:
        value: 3
  max_dsp_util:
    value: 95
  max_bram_util:
    value: 95
  alignedfactors:
    values: [True, False]
  bblock_generation:
    values: ['pre_while', 'post_while'] # pre_while or post_while
  bblock_keep_percentage:
    values: [0.25, 0.6, 1.0]
  use_arbitrary_shape:
    values: [True, False]
  use_previous_config:
    values: [True, False]
  chan_dist_thresh:
    values: [20, 60]
  depth_dist_thresh:
    value: 15
  height_dist_thresh:
    values: [20, 60]
# early_terminate:
#   type: hyperband
#   s: 2
#   eta: 3
#   max_iter: 27